
"drinkType"

INSERT INTO public."drinkType"(name) VALUES ('WINE');
INSERT INTO public."drinkType"(name) VALUES ('BEER');
INSERT INTO public."drinkType"(name) VALUES ('WHISKY');
INSERT INTO public."drinkType"(name) VALUES ('VODKA');
INSERT INTO public."drinkType"(name) VALUES ('GIN');
INSERT INTO public."drinkType"(name) VALUES ('TEQUILA');
INSERT INTO public."drinkType"(name) VALUES ('COGNAC');
INSERT INTO public."drinkType"(name) VALUES ('SODA');
INSERT INTO public."drinkType"(name) VALUES ('ENERGY');
INSERT INTO public."drinkType"(name) VALUES ('SOFT');

"country"
INSERT INTO public.country(id, name)vVALUES (1, 'Hrvatska');
"city"
INSERT INTO city (countryId,name) VALUES(1,'Zagreb');
INSERT INTO city (countryId,name) VALUES(1,'Split');
INSERT INTO city (countryId,name) VALUES(1,'Rijeka');
INSERT INTO city (countryId,name) VALUES(1,'Slavonski Brod');
INSERT INTO city (countryId,name) VALUES(1,'Osijek');
INSERT INTO city (countryId,name) VALUES(1,'Zadar');
INSERT INTO city (countryId,name) VALUES(1,'Pula');
INSERT INTO city (countryId,name) VALUES(1,'Karlovac');
INSERT INTO city (countryId,name) VALUES(1,'Šibenik');
INSERT INTO city (countryId,name) VALUES(1,'Dubrovnik');
INSERT INTO city (countryId,name) VALUES(1,'Luka');
INSERT INTO city (countryId,name) VALUES(1,'Lukač');
INSERT INTO city (countryId,name) VALUES(1,'Bol');
INSERT INTO city (countryId,name) VALUES(1,'Popovac');
INSERT INTO city (countryId,name) VALUES(1,'Zrinski Topolovac');
INSERT INTO city (countryId,name) VALUES(1,'Slano');
INSERT INTO city (countryId,name) VALUES(1,'Garčin');
INSERT INTO city (countryId,name) VALUES(1,'Jakšić');
INSERT INTO city (countryId,name) VALUES(1,'Podbablje');
INSERT INTO city (countryId,name) VALUES(1,'Klakar');
INSERT INTO city (countryId,name) VALUES(1,'Biograd na Moru');
INSERT INTO city (countryId,name) VALUES(1,'Vis');
INSERT INTO city (countryId,name) VALUES(1,'Krašić');
INSERT INTO city (countryId,name) VALUES(1,'Delnice');
INSERT INTO city (countryId,name) VALUES(1,'Rovišće');
INSERT INTO city (countryId,name) VALUES(1,'Rovinj');
INSERT INTO city (countryId,name) VALUES(1,'Labin');
INSERT INTO city (countryId,name) VALUES(1,'Bilice');
INSERT INTO city (countryId,name) VALUES(1,'Mikleuš');
INSERT INTO city (countryId,name) VALUES(1,'Ogulin');
INSERT INTO city (countryId,name) VALUES(1,'Žumberak');
INSERT INTO city (countryId,name) VALUES(1,'Solin');
INSERT INTO city (countryId,name) VALUES(1,'Čepin');
INSERT INTO city (countryId,name) VALUES(1,'Kukljica');
INSERT INTO city (countryId,name) VALUES(1,'Babino Polje');
INSERT INTO city (countryId,name) VALUES(1,'Povljana');
INSERT INTO city (countryId,name) VALUES(1,'Kaštelir');
INSERT INTO city (countryId,name) VALUES(1,'Rešetari');
INSERT INTO city (countryId,name) VALUES(1,'Lasinja');
INSERT INTO city (countryId,name) VALUES(1,'Galovac');
INSERT INTO city (countryId,name) VALUES(1,'Šodolovci');
INSERT INTO city (countryId,name) VALUES(1,'Kalinovac');
INSERT INTO city (countryId,name) VALUES(1,'Pribislavec');
INSERT INTO city (countryId,name) VALUES(1,'Jagodnjak');
INSERT INTO city (countryId,name) VALUES(1,'Podgorač');
INSERT INTO city (countryId,name) VALUES(1,'Orehovica');
INSERT INTO city (countryId,name) VALUES(1,'Donji Andrijevci');
INSERT INTO city (countryId,name) VALUES(1,'Dugopolje');
INSERT INTO city (countryId,name) VALUES(1,'Prelog');
INSERT INTO city (countryId,name) VALUES(1,'Donja Stubica');
INSERT INTO city (countryId,name) VALUES(1,'Vir');
INSERT INTO city (countryId,name) VALUES(1,'Petrinja');
INSERT INTO city (countryId,name) VALUES(1,'Gračac');
INSERT INTO city (countryId,name) VALUES(1,'Pakrac');
INSERT INTO city (countryId,name) VALUES(1,'Oklaj');
INSERT INTO city (countryId,name) VALUES(1,'Vojnić');
INSERT INTO city (countryId,name) VALUES(1,'Krnjak');
INSERT INTO city (countryId,name) VALUES(1,'Hercegovac');
INSERT INTO city (countryId,name) VALUES(1,'Saborsko');
INSERT INTO city (countryId,name) VALUES(1,'Pregrada');
INSERT INTO city (countryId,name) VALUES(1,'Otok');
INSERT INTO city (countryId,name) VALUES(1,'Sveti Martin na Muri');
INSERT INTO city (countryId,name) VALUES(1,'Brestovac');
INSERT INTO city (countryId,name) VALUES(1,'Žminj');
INSERT INTO city (countryId,name) VALUES(1,'Komiža');
INSERT INTO city (countryId,name) VALUES(1,'Prgomet');
INSERT INTO city (countryId,name) VALUES(1,'Sućuraj');
INSERT INTO city (countryId,name) VALUES(1,'Nova Kapela');
INSERT INTO city (countryId,name) VALUES(1,'Vrlika');
INSERT INTO city (countryId,name) VALUES(1,'Podcrkavlje');
INSERT INTO city (countryId,name) VALUES(1,'Klana');
INSERT INTO city (countryId,name) VALUES(1,'Antunovac');
INSERT INTO city (countryId,name) VALUES(1,'Novalja');
INSERT INTO city (countryId,name) VALUES(1,'Topusko');
INSERT INTO city (countryId,name) VALUES(1,'Mali Bukovec');
INSERT INTO city (countryId,name) VALUES(1,'Brinje');
INSERT INTO city (countryId,name) VALUES(1,'Vodice');
INSERT INTO city (countryId,name) VALUES(1,'Otrić-Seoci');
INSERT INTO city (countryId,name) VALUES(1,'Ploče');
INSERT INTO city (countryId,name) VALUES(1,'Ružić');
INSERT INTO city (countryId,name) VALUES(1,'Rakovec');
INSERT INTO city (countryId,name) VALUES(1,'Tuhelj');
INSERT INTO city (countryId,name) VALUES(1,'Gornja Rijeka');
INSERT INTO city (countryId,name) VALUES(1,'Bošnjaci');
INSERT INTO city (countryId,name) VALUES(1,'Petrijanec');
INSERT INTO city (countryId,name) VALUES(1,'Orle');
INSERT INTO city (countryId,name) VALUES(1,'Biskupija');
INSERT INTO city (countryId,name) VALUES(1,'Lobor');
INSERT INTO city (countryId,name) VALUES(1,'Desinić');
INSERT INTO city (countryId,name) VALUES(1,'Šestanovac');
INSERT INTO city (countryId,name) VALUES(1,'Kistanje');
INSERT INTO city (countryId,name) VALUES(1,'Novi Golubovec');
INSERT INTO city (countryId,name) VALUES(1,'Ozalj');
INSERT INTO city (countryId,name) VALUES(1,'Peteranec');
INSERT INTO city (countryId,name) VALUES(1,'Milna');
INSERT INTO city (countryId,name) VALUES(1,'Oriovac');
INSERT INTO city (countryId,name) VALUES(1,'Dragalić');
INSERT INTO city (countryId,name) VALUES(1,'Voćin');
INSERT INTO city (countryId,name) VALUES(1,'Donji Miholjac');
INSERT INTO city (countryId,name) VALUES(1,'Lumbarda');
INSERT INTO city (countryId,name) VALUES(1,'Severin');
INSERT INTO city (countryId,name) VALUES(1,'Sveti Ivan Zelina');
INSERT INTO city (countryId,name) VALUES(1,'Buje');
INSERT INTO city (countryId,name) VALUES(1,'Brtonigla');
INSERT INTO city (countryId,name) VALUES(1,'Nerežišće');
INSERT INTO city (countryId,name) VALUES(1,'Lećevica');
INSERT INTO city (countryId,name) VALUES(1,'Dvor');
INSERT INTO city (countryId,name) VALUES(1,'Matulji');
INSERT INTO city (countryId,name) VALUES(1,'Goričan');
INSERT INTO city (countryId,name) VALUES(1,'Vlaka');
INSERT INTO city (countryId,name) VALUES(1,'Brckovljani');
INSERT INTO city (countryId,name) VALUES(1,'Donji Kukuruzari');
INSERT INTO city (countryId,name) VALUES(1,'Kloštar Podravski');
INSERT INTO city (countryId,name) VALUES(1,'Kloštar Ivanić');
INSERT INTO city (countryId,name) VALUES(1,'Darda');
INSERT INTO city (countryId,name) VALUES(1,'Daruvar');
INSERT INTO city (countryId,name) VALUES(1,'Vrhovine');
INSERT INTO city (countryId,name) VALUES(1,'Nova Rača');
INSERT INTO city (countryId,name) VALUES(1,'Tar');
INSERT INTO city (countryId,name) VALUES(1,'Zemunik Donji');
INSERT INTO city (countryId,name) VALUES(1,'Klis');
INSERT INTO city (countryId,name) VALUES(1,'Petlovac');
INSERT INTO city (countryId,name) VALUES(1,'Vrsar');
INSERT INTO city (countryId,name) VALUES(1,'Dekanovec');
INSERT INTO city (countryId,name) VALUES(1,'Ðurđenovac');
INSERT INTO city (countryId,name) VALUES(1,'Ðurđevac');
INSERT INTO city (countryId,name) VALUES(1,'Čazma');
INSERT INTO city (countryId,name) VALUES(1,'Rugvica');
INSERT INTO city (countryId,name) VALUES(1,'Buzet');
INSERT INTO city (countryId,name) VALUES(1,'Cernik');
INSERT INTO city (countryId,name) VALUES(1,'Levanjska Varoš');
INSERT INTO city (countryId,name) VALUES(1,'Gradište');
INSERT INTO city (countryId,name) VALUES(1,'Požega');
INSERT INTO city (countryId,name) VALUES(1,'Barilović');
INSERT INTO city (countryId,name) VALUES(1,'Pićan');
INSERT INTO city (countryId,name) VALUES(1,'Tompojevci');
INSERT INTO city (countryId,name) VALUES(1,'Trnovec Bartolovečki');
INSERT INTO city (countryId,name) VALUES(1,'Budinšćina');
INSERT INTO city (countryId,name) VALUES(1,'Čačinci');
INSERT INTO city (countryId,name) VALUES(1,'Fažana');
INSERT INTO city (countryId,name) VALUES(1,'Bednja');
INSERT INTO city (countryId,name) VALUES(1,'Bedenica');
INSERT INTO city (countryId,name) VALUES(1,'Imotski');
INSERT INTO city (countryId,name) VALUES(1,'Perušić');
INSERT INTO city (countryId,name) VALUES(1,'Hrvace');
INSERT INTO city (countryId,name) VALUES(1,'Gornji Stupnik');
INSERT INTO city (countryId,name) VALUES(1,'Novi Marof');
INSERT INTO city (countryId,name) VALUES(1,'Bilje');
INSERT INTO city (countryId,name) VALUES(1,'Kumrovec');
INSERT INTO city (countryId,name) VALUES(1,'Sveti Ilija');
INSERT INTO city (countryId,name) VALUES(1,'Mursko Središće');
INSERT INTO city (countryId,name) VALUES(1,'Metković');
INSERT INTO city (countryId,name) VALUES(1,'Lekenik');
INSERT INTO city (countryId,name) VALUES(1,'Županja');
INSERT INTO city (countryId,name) VALUES(1,'Podstrana');
INSERT INTO city (countryId,name) VALUES(1,'Vrbnik');
INSERT INTO city (countryId,name) VALUES(1,'Rasinja');
INSERT INTO city (countryId,name) VALUES(1,'Veliki Bukovec');
INSERT INTO city (countryId,name) VALUES(1,'Omišalj');
INSERT INTO city (countryId,name) VALUES(1,'Lovinac');
INSERT INTO city (countryId,name) VALUES(1,'Umag');
INSERT INTO city (countryId,name) VALUES(1,'Srebreno');
INSERT INTO city (countryId,name) VALUES(1,'Dežanovac');
INSERT INTO city (countryId,name) VALUES(1,'Medulin');
INSERT INTO city (countryId,name) VALUES(1,'Orahovica');
INSERT INTO city (countryId,name) VALUES(1,'Baška');
INSERT INTO city (countryId,name) VALUES(1,'Kutina');
INSERT INTO city (countryId,name) VALUES(1,'Generalski Stol');
INSERT INTO city (countryId,name) VALUES(1,'Velika Gorica');
INSERT INTO city (countryId,name) VALUES(1,'Slavonski Šamac');
INSERT INTO city (countryId,name) VALUES(1,'Dugi Rat');
INSERT INTO city (countryId,name) VALUES(1,'Mrkopalj');
INSERT INTO city (countryId,name) VALUES(1,'Vukovar');
INSERT INTO city (countryId,name) VALUES(1,'Oroslavje');
INSERT INTO city (countryId,name) VALUES(1,'Donji Vidovec');
INSERT INTO city (countryId,name) VALUES(1,'Lokve');
INSERT INTO city (countryId,name) VALUES(1,'Mali Lošinj');
INSERT INTO city (countryId,name) VALUES(1,'Babina Greda');
INSERT INTO city (countryId,name) VALUES(1,'Tribunj');
INSERT INTO city (countryId,name) VALUES(1,'Oprisavci');
INSERT INTO city (countryId,name) VALUES(1,'Oprtalj');
INSERT INTO city (countryId,name) VALUES(1,'Staro Petrovo Selo');
INSERT INTO city (countryId,name) VALUES(1,'Kostrena');
INSERT INTO city (countryId,name) VALUES(1,'Primorski Dolac');
INSERT INTO city (countryId,name) VALUES(1,'Visoko');
INSERT INTO city (countryId,name) VALUES(1,'Samobor');
INSERT INTO city (countryId,name) VALUES(1,'Jesenice');
INSERT INTO city (countryId,name) VALUES(1,'Hrvatska Dubica');
INSERT INTO city (countryId,name) VALUES(1,'Varaždinske Toplice');
INSERT INTO city (countryId,name) VALUES(1,'Varaždin');
INSERT INTO city (countryId,name) VALUES(1,'Velika Trnovitica');
INSERT INTO city (countryId,name) VALUES(1,'Petrovsko');
INSERT INTO city (countryId,name) VALUES(1,'Nin');
INSERT INTO city (countryId,name) VALUES(1,'Zagvozd');
INSERT INTO city (countryId,name) VALUES(1,'Stankovci');
INSERT INTO city (countryId,name) VALUES(1,'Zmijavci');
INSERT INTO city (countryId,name) VALUES(1,'Punitovci');
INSERT INTO city (countryId,name) VALUES(1,'Ražanac');
INSERT INTO city (countryId,name) VALUES(1,'Jasenovac');
INSERT INTO city (countryId,name) VALUES(1,'Bale');
INSERT INTO city (countryId,name) VALUES(1,'Trpanj');
INSERT INTO city (countryId,name) VALUES(1,'Ilok');
INSERT INTO city (countryId,name) VALUES(1,'Pag');
INSERT INTO city (countryId,name) VALUES(1,'Ervenik');
INSERT INTO city (countryId,name) VALUES(1,'Privlaka');
INSERT INTO city (countryId,name) VALUES(1,'Ivanska');
INSERT INTO city (countryId,name) VALUES(1,'Kolan');
INSERT INTO city (countryId,name) VALUES(1,'Lipovljani');
INSERT INTO city (countryId,name) VALUES(1,'Valpovo');
INSERT INTO city (countryId,name) VALUES(1,'Markušica');
INSERT INTO city (countryId,name) VALUES(1,'Skradin');
INSERT INTO city (countryId,name) VALUES(1,'Donji Lapac');
INSERT INTO city (countryId,name) VALUES(1,'Mala Subotica');
INSERT INTO city (countryId,name) VALUES(1,'Martijanec');
INSERT INTO city (countryId,name) VALUES(1,'Sveti Petar u Šumi');
INSERT INTO city (countryId,name) VALUES(1,'Murter');
INSERT INTO city (countryId,name) VALUES(1,'Podravske Sesvete');
INSERT INTO city (countryId,name) VALUES(1,'Gornji Mihaljevec');
INSERT INTO city (countryId,name) VALUES(1,'Crnac');
INSERT INTO city (countryId,name) VALUES(1,'Breznica');
INSERT INTO city (countryId,name) VALUES(1,'Gradec');
INSERT INTO city (countryId,name) VALUES(1,'Brela');
INSERT INTO city (countryId,name) VALUES(1,'Brdovec');
INSERT INTO city (countryId,name) VALUES(1,'Radoboj');
INSERT INTO city (countryId,name) VALUES(1,'Hrašćina');
INSERT INTO city (countryId,name) VALUES(1,'Stari Mikanovci');
INSERT INTO city (countryId,name) VALUES(1,'Rogoznica');
INSERT INTO city (countryId,name) VALUES(1,'Ivankovo');
INSERT INTO city (countryId,name) VALUES(1,'Omiš');
INSERT INTO city (countryId,name) VALUES(1,'Jelsa');
INSERT INTO city (countryId,name) VALUES(1,'Zagorska Sela');
INSERT INTO city (countryId,name) VALUES(1,'Duga Resa');
INSERT INTO city (countryId,name) VALUES(1,'Sinj');
INSERT INTO city (countryId,name) VALUES(1,'Semeljci');
INSERT INTO city (countryId,name) VALUES(1,'Viljevo');
INSERT INTO city (countryId,name) VALUES(1,'Belišće');
INSERT INTO city (countryId,name) VALUES(1,'Gundinci');
INSERT INTO city (countryId,name) VALUES(1,'Gunja');
INSERT INTO city (countryId,name) VALUES(1,'Križ');
INSERT INTO city (countryId,name) VALUES(1,'Bedekovčina');
INSERT INTO city (countryId,name) VALUES(1,'Klinča Sela');
INSERT INTO city (countryId,name) VALUES(1,'Udbina');
INSERT INTO city (countryId,name) VALUES(1,'Andrijaševci');
INSERT INTO city (countryId,name) VALUES(1,'Nedeščina');
INSERT INTO city (countryId,name) VALUES(1,'Nedelišće');
INSERT INTO city (countryId,name) VALUES(1,'Sveti Filip i Jakov');
INSERT INTO city (countryId,name) VALUES(1,'Koška');
INSERT INTO city (countryId,name) VALUES(1,'Mače');
INSERT INTO city (countryId,name) VALUES(1,'Starigrad');
INSERT INTO city (countryId,name) VALUES(1,'Sibinj');
INSERT INTO city (countryId,name) VALUES(1,'Ivanić-Grad');
INSERT INTO city (countryId,name) VALUES(1,'Pleternica');
INSERT INTO city (countryId,name) VALUES(1,'Špišić-Bukovica');
INSERT INTO city (countryId,name) VALUES(1,'Bebrina');
INSERT INTO city (countryId,name) VALUES(1,'Garešnica');
INSERT INTO city (countryId,name) VALUES(1,'Slunj');
INSERT INTO city (countryId,name) VALUES(1,'Preko');
INSERT INTO city (countryId,name) VALUES(1,'Vladislavci');
INSERT INTO city (countryId,name) VALUES(1,'Zabok');
INSERT INTO city (countryId,name) VALUES(1,'Sveti Ivan Žabno');
INSERT INTO city (countryId,name) VALUES(1,'Marina');
INSERT INTO city (countryId,name) VALUES(1,'Lepoglava');
INSERT INTO city (countryId,name) VALUES(1,'Supetar');
INSERT INTO city (countryId,name) VALUES(1,'Cista Provo');
INSERT INTO city (countryId,name) VALUES(1,'Ribnik');
INSERT INTO city (countryId,name) VALUES(1,'Vrbovsko');
INSERT INTO city (countryId,name) VALUES(1,'Mihovljan');
INSERT INTO city (countryId,name) VALUES(1,'Pirovac');
INSERT INTO city (countryId,name) VALUES(1,'Breznički Hum');
INSERT INTO city (countryId,name) VALUES(1,'Vrbanja');
INSERT INTO city (countryId,name) VALUES(1,'Donja Voća');
INSERT INTO city (countryId,name) VALUES(1,'Poreč');
INSERT INTO city (countryId,name) VALUES(1,'Trogir');
INSERT INTO city (countryId,name) VALUES(1,'Mošćenička Draga');
INSERT INTO city (countryId,name) VALUES(1,'Drniš');
INSERT INTO city (countryId,name) VALUES(1,'Koprivnički Bregi');
INSERT INTO city (countryId,name) VALUES(1,'Vratišinec');
INSERT INTO city (countryId,name) VALUES(1,'Josipdol');
INSERT INTO city (countryId,name) VALUES(1,'Donja Motičina');
INSERT INTO city (countryId,name) VALUES(1,'Posedarje');
INSERT INTO city (countryId,name) VALUES(1,'Krapina');
INSERT INTO city (countryId,name) VALUES(1,'Krapinske Toplice');
INSERT INTO city (countryId,name) VALUES(1,'Ferdinandovac');
INSERT INTO city (countryId,name) VALUES(1,'Cestica');
INSERT INTO city (countryId,name) VALUES(1,'Našice');
INSERT INTO city (countryId,name) VALUES(1,'Sutivan');
INSERT INTO city (countryId,name) VALUES(1,'Štefanje');
INSERT INTO city (countryId,name) VALUES(1,'Rakovica');
INSERT INTO city (countryId,name) VALUES(1,'Gola');
INSERT INTO city (countryId,name) VALUES(1,'Korenica');
INSERT INTO city (countryId,name) VALUES(1,'Ðulovac');
INSERT INTO city (countryId,name) VALUES(1,'Kastav');
INSERT INTO city (countryId,name) VALUES(1,'Gornji Kneginec');
INSERT INTO city (countryId,name) VALUES(1,'Klanjec');
INSERT INTO city (countryId,name) VALUES(1,'Podgora');
INSERT INTO city (countryId,name) VALUES(1,'Sveti Petar Orehovec');
INSERT INTO city (countryId,name) VALUES(1,'Orebić');
INSERT INTO city (countryId,name) VALUES(1,'Sisak');
INSERT INTO city (countryId,name) VALUES(1,'Sveti Križ Začretje');
INSERT INTO city (countryId,name) VALUES(1,'Kneževi Vinogradi');
INSERT INTO city (countryId,name) VALUES(1,'Virje');
INSERT INTO city (countryId,name) VALUES(1,'Virovitica');
INSERT INTO city (countryId,name) VALUES(1,'Donja Pušća');
INSERT INTO city (countryId,name) VALUES(1,'Čaglin');
INSERT INTO city (countryId,name) VALUES(1,'Ravna Gora');
INSERT INTO city (countryId,name) VALUES(1,'Marčana');
INSERT INTO city (countryId,name) VALUES(1,'Karlobag');
INSERT INTO city (countryId,name) VALUES(1,'Pitomača');
INSERT INTO city (countryId,name) VALUES(1,'Otočac');
INSERT INTO city (countryId,name) VALUES(1,'Stara Gradiška');
INSERT INTO city (countryId,name) VALUES(1,'Gradina');
INSERT INTO city (countryId,name) VALUES(1,'Ližnjan');
INSERT INTO city (countryId,name) VALUES(1,'Lanišće');
INSERT INTO city (countryId,name) VALUES(1,'Viškovci');
INSERT INTO city (countryId,name) VALUES(1,'Ljubešćica');
INSERT INTO city (countryId,name) VALUES(1,'Tučepi');
INSERT INTO city (countryId,name) VALUES(1,'Satnica Ðakovačka');
INSERT INTO city (countryId,name) VALUES(1,'Unešić');
INSERT INTO city (countryId,name) VALUES(1,'Kaštel Sućurac');
INSERT INTO city (countryId,name) VALUES(1,'Benkovac');
INSERT INTO city (countryId,name) VALUES(1,'Velika Kopanica');
INSERT INTO city (countryId,name) VALUES(1,'Molve');
INSERT INTO city (countryId,name) VALUES(1,'Končanica');
INSERT INTO city (countryId,name) VALUES(1,'Nuštar');
INSERT INTO city (countryId,name) VALUES(1,'Sukošan');
INSERT INTO city (countryId,name) VALUES(1,'Lastovo');
INSERT INTO city (countryId,name) VALUES(1,'Novigrad');
INSERT INTO city (countryId,name) VALUES(1,'Vođinci');
INSERT INTO city (countryId,name) VALUES(1,'Hvar');
INSERT INTO city (countryId,name) VALUES(1,'Civljane');
INSERT INTO city (countryId,name) VALUES(1,'Sunja');
INSERT INTO city (countryId,name) VALUES(1,'Skrad');
INSERT INTO city (countryId,name) VALUES(1,'Ludbreg');
INSERT INTO city (countryId,name) VALUES(1,'Motovun');
INSERT INTO city (countryId,name) VALUES(1,'Glina');
INSERT INTO city (countryId,name) VALUES(1,'Grubišno Polje');
INSERT INTO city (countryId,name) VALUES(1,'Tinjan');
INSERT INTO city (countryId,name) VALUES(1,'Baška Voda');
INSERT INTO city (countryId,name) VALUES(1,'Draž');
INSERT INTO city (countryId,name) VALUES(1,'Postire');
INSERT INTO city (countryId,name) VALUES(1,'Jakovlje');
INSERT INTO city (countryId,name) VALUES(1,'Klenovnik');
INSERT INTO city (countryId,name) VALUES(1,'Vrgorac');
INSERT INTO city (countryId,name) VALUES(1,'Gvozd');
INSERT INTO city (countryId,name) VALUES(1,'Zlatar Bistrica');
INSERT INTO city (countryId,name) VALUES(1,'Višnjan');
INSERT INTO city (countryId,name) VALUES(1,'Čeminac');
INSERT INTO city (countryId,name) VALUES(1,'Cetingrad');
INSERT INTO city (countryId,name) VALUES(1,'Tordinci');
INSERT INTO city (countryId,name) VALUES(1,'Berek');
INSERT INTO city (countryId,name) VALUES(1,'Beretinec');
INSERT INTO city (countryId,name) VALUES(1,'Lokvičič');
INSERT INTO city (countryId,name) VALUES(1,'Grožnjan');
INSERT INTO city (countryId,name) VALUES(1,'Hlebine');
INSERT INTO city (countryId,name) VALUES(1,'Drenovci');
INSERT INTO city (countryId,name) VALUES(1,'Barban');
INSERT INTO city (countryId,name) VALUES(1,'Dubravica');
INSERT INTO city (countryId,name) VALUES(1,'Knin');
INSERT INTO city (countryId,name) VALUES(1,'Suhopolje');
INSERT INTO city (countryId,name) VALUES(1,'Bosiljevo');
INSERT INTO city (countryId,name) VALUES(1,'Mlinište');
INSERT INTO city (countryId,name) VALUES(1,'Runović');
INSERT INTO city (countryId,name) VALUES(1,'Netretić');
INSERT INTO city (countryId,name) VALUES(1,'Petrijevci');
INSERT INTO city (countryId,name) VALUES(1,'Jalžabet');
INSERT INTO city (countryId,name) VALUES(1,'Gradac');
INSERT INTO city (countryId,name) VALUES(1,'Selca');
INSERT INTO city (countryId,name) VALUES(1,'Davor');
INSERT INTO city (countryId,name) VALUES(1,'Lupoglav');
INSERT INTO city (countryId,name) VALUES(1,'Grohote');
INSERT INTO city (countryId,name) VALUES(1,'Sokolovac');
INSERT INTO city (countryId,name) VALUES(1,'Kršan');
INSERT INTO city (countryId,name) VALUES(1,'Sikirevci');
INSERT INTO city (countryId,name) VALUES(1,'Svetvinčenat');
INSERT INTO city (countryId,name) VALUES(1,'Sračinec');
INSERT INTO city (countryId,name) VALUES(1,'Jarmina');
INSERT INTO city (countryId,name) VALUES(1,'Donji Muć');
INSERT INTO city (countryId,name) VALUES(1,'Nova Gradiška');
INSERT INTO city (countryId,name) VALUES(1,'Pazin');
INSERT INTO city (countryId,name) VALUES(1,'Maruševec');
INSERT INTO city (countryId,name) VALUES(1,'Poljanica Bistranska');
INSERT INTO city (countryId,name) VALUES(1,'Kaptol');
INSERT INTO city (countryId,name) VALUES(1,'Čabar');
INSERT INTO city (countryId,name) VALUES(1,'Brodski Stupnik');
INSERT INTO city (countryId,name) VALUES(1,'Lišane Ostrovičke');
INSERT INTO city (countryId,name) VALUES(1,'Veliko Trojstvo');
INSERT INTO city (countryId,name) VALUES(1,'Veliko Trgovišće');
INSERT INTO city (countryId,name) VALUES(1,'Okučani');
INSERT INTO city (countryId,name) VALUES(1,'Drenje');
INSERT INTO city (countryId,name) VALUES(1,'Kula Norinska');
INSERT INTO city (countryId,name) VALUES(1,'Lopar');
INSERT INTO city (countryId,name) VALUES(1,'Kotoriba');
INSERT INTO city (countryId,name) VALUES(1,'Gospić');
INSERT INTO city (countryId,name) VALUES(1,'Tisno');
INSERT INTO city (countryId,name) VALUES(1,'Zdenci');
INSERT INTO city (countryId,name) VALUES(1,'Marija Gorica');
INSERT INTO city (countryId,name) VALUES(1,'Gornji Bogičevci');
INSERT INTO city (countryId,name) VALUES(1,'Draganići');
INSERT INTO city (countryId,name) VALUES(1,'Kraljevica');
INSERT INTO city (countryId,name) VALUES(1,'Kraljevec na Sutli');
INSERT INTO city (countryId,name) VALUES(1,'Dobrinj');
INSERT INTO city (countryId,name) VALUES(1,'Ðurmanec');
INSERT INTO city (countryId,name) VALUES(1,'Sveti Ðurđ');
INSERT INTO city (countryId,name) VALUES(1,'Čađavica');
INSERT INTO city (countryId,name) VALUES(1,'Sirač');
INSERT INTO city (countryId,name) VALUES(1,'Janjina');
INSERT INTO city (countryId,name) VALUES(1,'Strizivojna');
INSERT INTO city (countryId,name) VALUES(1,'Gornja Vrba');
INSERT INTO city (countryId,name) VALUES(1,'Ðelekovec');
INSERT INTO city (countryId,name) VALUES(1,'Vižinada');
INSERT INTO city (countryId,name) VALUES(1,'Cavtat');
INSERT INTO city (countryId,name) VALUES(1,'Čavle');
INSERT INTO city (countryId,name) VALUES(1,'Gorjani');
INSERT INTO city (countryId,name) VALUES(1,'Novo Virje');
INSERT INTO city (countryId,name) VALUES(1,'Opatija');
INSERT INTO city (countryId,name) VALUES(1,'Farkaševac');
INSERT INTO city (countryId,name) VALUES(1,'Drnje');
INSERT INTO city (countryId,name) VALUES(1,'Veliki Grđevac');
INSERT INTO city (countryId,name) VALUES(1,'Dugo Selo');
INSERT INTO city (countryId,name) VALUES(1,'Ðakovo');
INSERT INTO city (countryId,name) VALUES(1,'Kali');
INSERT INTO city (countryId,name) VALUES(1,'Funtana');
INSERT INTO city (countryId,name) VALUES(1,'Sopje');
INSERT INTO city (countryId,name) VALUES(1,'Cres');
INSERT INTO city (countryId,name) VALUES(1,'Štrigova');
INSERT INTO city (countryId,name) VALUES(1,'Vrbovec');
INSERT INTO city (countryId,name) VALUES(1,'Vrsi');
INSERT INTO city (countryId,name) VALUES(1,'Lopatinec');
INSERT INTO city (countryId,name) VALUES(1,'Makarska');
INSERT INTO city (countryId,name) VALUES(1,'Kutjevo');
INSERT INTO city (countryId,name) VALUES(1,'Tounj');
INSERT INTO city (countryId,name) VALUES(1,'Belica');
INSERT INTO city (countryId,name) VALUES(1,'Nova Bukovica');
INSERT INTO city (countryId,name) VALUES(1,'Velika');
INSERT INTO city (countryId,name) VALUES(1,'Novigrad Podravski');
INSERT INTO city (countryId,name) VALUES(1,'Gornje Jesenje');
INSERT INTO city (countryId,name) VALUES(1,'Sveta Marija');
INSERT INTO city (countryId,name) VALUES(1,'Sveta Nedjelja');
INSERT INTO city (countryId,name) VALUES(1,'Koprivnica');
INSERT INTO city (countryId,name) VALUES(1,'Popovača');
INSERT INTO city (countryId,name) VALUES(1,'Crikvenica');
INSERT INTO city (countryId,name) VALUES(1,'Čakovec');
INSERT INTO city (countryId,name) VALUES(1,'Kijevo');
INSERT INTO city (countryId,name) VALUES(1,'Vrbje');
INSERT INTO city (countryId,name) VALUES(1,'Plaški');
INSERT INTO city (countryId,name) VALUES(1,'Smokvica');
INSERT INTO city (countryId,name) VALUES(1,'Šandrovac');
INSERT INTO city (countryId,name) VALUES(1,'Raša');
INSERT INTO city (countryId,name) VALUES(1,'Trpinja');
INSERT INTO city (countryId,name) VALUES(1,'Kapela');
INSERT INTO city (countryId,name) VALUES(1,'Borovo');
INSERT INTO city (countryId,name) VALUES(1,'Pokupsko');
INSERT INTO city (countryId,name) VALUES(1,'Lovas');
INSERT INTO city (countryId,name) VALUES(1,'Sali');
INSERT INTO city (countryId,name) VALUES(1,'Primošten');
INSERT INTO city (countryId,name) VALUES(1,'Bakar');
INSERT INTO city (countryId,name) VALUES(1,'Martinska Ves');
INSERT INTO city (countryId,name) VALUES(1,'Marjanci');
INSERT INTO city (countryId,name) VALUES(1,'Vidovec');
INSERT INTO city (countryId,name) VALUES(1,'Stubičke Toplice');
INSERT INTO city (countryId,name) VALUES(1,'Donji Proložac');
INSERT INTO city (countryId,name) VALUES(1,'Lovran');
INSERT INTO city (countryId,name) VALUES(1,'Lovreć');
INSERT INTO city (countryId,name) VALUES(1,'Sveti Lovreč Pazenatički');
INSERT INTO city (countryId,name) VALUES(1,'Kalnik');
INSERT INTO city (countryId,name) VALUES(1,'Štitar');
INSERT INTO city (countryId,name) VALUES(1,'Novi Vinodolski');
INSERT INTO city (countryId,name) VALUES(1,'Trilj');
INSERT INTO city (countryId,name) VALUES(1,'Bukovlje');
INSERT INTO city (countryId,name) VALUES(1,'Legrad');
INSERT INTO city (countryId,name) VALUES(1,'Kraj');
INSERT INTO city (countryId,name) VALUES(1,'Žakanje');
INSERT INTO city (countryId,name) VALUES(1,'Pašman');
INSERT INTO city (countryId,name) VALUES(1,'Brod Moravice');
INSERT INTO city (countryId,name) VALUES(1,'Domašinec');
INSERT INTO city (countryId,name) VALUES(1,'Pučišće');
INSERT INTO city (countryId,name) VALUES(1,'Tovarnik');
INSERT INTO city (countryId,name) VALUES(1,'Korčula');
INSERT INTO city (countryId,name) VALUES(1,'Ston');
INSERT INTO city (countryId,name) VALUES(1,'Slatina');
INSERT INTO city (countryId,name) VALUES(1,'Okrug Gornji');
INSERT INTO city (countryId,name) VALUES(1,'Bogdanovci');
INSERT INTO city (countryId,name) VALUES(1,'Donji Seget');
INSERT INTO city (countryId,name) VALUES(1,'Rab');
INSERT INTO city (countryId,name) VALUES(1,'Kamanje');
INSERT INTO city (countryId,name) VALUES(1,'Kanfanar');
INSERT INTO city (countryId,name) VALUES(1,'Cerovlje');
INSERT INTO city (countryId,name) VALUES(1,'Zlatar');
INSERT INTO city (countryId,name) VALUES(1,'Koprivnički Ivanec');
INSERT INTO city (countryId,name) VALUES(1,'Donji Kraljevec');
INSERT INTO city (countryId,name) VALUES(1,'Punat');
INSERT INTO city (countryId,name) VALUES(1,'Dubrava');
INSERT INTO city (countryId,name) VALUES(1,'Lipik');
INSERT INTO city (countryId,name) VALUES(1,'Beli Manastir');
INSERT INTO city (countryId,name) VALUES(1,'Obrovac');
INSERT INTO city (countryId,name) VALUES(1,'Jastrebarsko');
INSERT INTO city (countryId,name) VALUES(1,'Kravarsko');
INSERT INTO city (countryId,name) VALUES(1,'Negoslavci');
INSERT INTO city (countryId,name) VALUES(1,'Podravska Moslavina');
INSERT INTO city (countryId,name) VALUES(1,'Viškovo');
INSERT INTO city (countryId,name) VALUES(1,'Magadenovac');
INSERT INTO city (countryId,name) VALUES(1,'Feričanci');
INSERT INTO city (countryId,name) VALUES(1,'Zadvarje');
INSERT INTO city (countryId,name) VALUES(1,'Bjelovar');
INSERT INTO city (countryId,name) VALUES(1,'Stari Jankovci');
INSERT INTO city (countryId,name) VALUES(1,'Preseka');
INSERT INTO city (countryId,name) VALUES(1,'Erdut');
INSERT INTO city (countryId,name) VALUES(1,'Jelenje');
INSERT INTO city (countryId,name) VALUES(1,'Strahoninec');
INSERT INTO city (countryId,name) VALUES(1,'Šenkovec');
INSERT INTO city (countryId,name) VALUES(1,'Novska');
INSERT INTO city (countryId,name) VALUES(1,'Bibinje');
INSERT INTO city (countryId,name) VALUES(1,'Križevci');
INSERT INTO city (countryId,name) VALUES(1,'Fužine');
INSERT INTO city (countryId,name) VALUES(1,'Blato');
INSERT INTO city (countryId,name) VALUES(1,'Škabrnje');
INSERT INTO city (countryId,name) VALUES(1,'Bizovac');
INSERT INTO city (countryId,name) VALUES(1,'Gornja Stubica');
INSERT INTO city (countryId,name) VALUES(1,'Vela Luka');
INSERT INTO city (countryId,name) VALUES(1,'Vinkovci');
INSERT INTO city (countryId,name) VALUES(1,'Marija Bistrica');
INSERT INTO city (countryId,name) VALUES(1,'Malinska');
INSERT INTO city (countryId,name) VALUES(1,'Krk');
INSERT INTO city (countryId,name) VALUES(1,'Poličnik');
INSERT INTO city (countryId,name) VALUES(1,'Pakoštane');
INSERT INTO city (countryId,name) VALUES(1,'Zaprešić');
INSERT INTO city (countryId,name) VALUES(1,'Velika Ludina');
INSERT INTO city (countryId,name) VALUES(1,'Hum na Sutli');
INSERT INTO city (countryId,name) VALUES(1,'Senj');
INSERT INTO city (countryId,name) VALUES(1,'Nijemci');
INSERT INTO city (countryId,name) VALUES(1,'Trnava');
INSERT INTO city (countryId,name) VALUES(1,'Velika Pisanica');
INSERT INTO city (countryId,name) VALUES(1,'Karojba');
INSERT INTO city (countryId,name) VALUES(1,'Opuzen');
INSERT INTO city (countryId,name) VALUES(1,'Gračišće');
INSERT INTO city (countryId,name) VALUES(1,'Vrpolje');
INSERT INTO city (countryId,name) VALUES(1,'Konjšćina');
INSERT INTO city (countryId,name) VALUES(1,'Selnica');
INSERT INTO city (countryId,name) VALUES(1,'Vuka');
INSERT INTO city (countryId,name) VALUES(1,'Vinica');
INSERT INTO city (countryId,name) VALUES(1,'Donja Dubrava');
INSERT INTO city (countryId,name) VALUES(1,'Vodnjan');
INSERT INTO city (countryId,name) VALUES(1,'Majur');
INSERT INTO city (countryId,name) VALUES(1,'Hrvatska Kostajnica');
INSERT INTO city (countryId,name) VALUES(1,'Ernestinovo');
INSERT INTO city (countryId,name) VALUES(1,'Polača');
INSERT INTO city (countryId,name) VALUES(1,'Pisarovina');
INSERT INTO city (countryId,name) VALUES(1,'Ivanec');
INSERT INTO city (countryId,name) VALUES(1,'Bribir');
INSERT INTO city (countryId,name) VALUES(1,'Podturen');
INSERT INTO city (countryId,name) VALUES(1,'Cerna');

"tableType"
INSERT INTO public."tableType"(name) VALUES ('Vip');
INSERT INTO public."tableType"(name) VALUES ('Basic');