export const LOGIN_USER = 'LOGIN_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const AUTH_USER = 'AUTH_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
// get reservations request
export const RESERVATIONS_LIST_REQUEST = 'RESERVATIONS_LIST_REQUEST';
export const RESERVATIONS_LIST_SUCCESS = 'RESERVATIONS_LIST_SUCCESS';
export const RESERVATIONS_LIST_FAIL = 'RESERVATIONS_LIST_FAIL';
// delete reservations request
export const RESERVATION_DELETE_REQUEST = 'RESERVATION_DELETE_REQUEST';
export const RESERVATION_DELETE_SUCCESS = 'RESERVATION_DELETE_SUCCESS';
export const RESERVATION_DELETE_FAIL = 'RESERVATION_DELETE_FAIL';
// get clubs request
export const CLUBS_LIST_REQUEST = 'CLUBS_LIST_REQUEST';
export const CLUBS_LIST_SUCCESS = 'CLUBS_LIST_SUCCESS';
export const CLUBS_LIST_FAIL = 'CLUBS_LIST_FAIL';
// get clubs tables request
export const FREETABLES_LIST_REQUEST = 'FREETABLES_LIST_REQUEST';
export const FREETABLES_LIST_SUCCESS = 'FREETABLES_LIST_SUCCESS';
export const FREETABLES_LIST_FAIL = 'FREETABLES_LIST_FAIL';
// post reservation
export const POST_RESERVATION_REQUEST = 'POST_RESERVATION_REQUEST';
export const POST_RESERVATION_SUCCESS = 'POST_RESERVATION_SUCCESS';
export const POST_RESERVATION_FAIL = 'POST_RESERVATION_FAIL';
